# Generated by Django 5.2.1 on 2025-05-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplements', '0002_alter_supplement_id_alter_vendor_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supplementinventory',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='supplement',
            name='suplements__name_67394d_idx',
        ),
    ]
